export default {
  products: [
    {
      id: 1,
      car_make_name: "Suzuki",
      car_model_name: "Verona",
      car_model_year: 2005,
      price: 3287,
      image: "http://dummyimage.com/300x300.png/cc0000/ffffff",
      if_favorite: false,
      stock: 1,
    },
    {
      id: 2,
      car_make_name: "Lexus",
      car_model_name: "ES",
      car_model_year: 1989,
      price: 989,
      image: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
      if_favorite: false,
      stock: 11,
    },
    {
      id: 3,
      car_make_name: "Chrysler",
      car_model_name: "300",
      car_model_year: 2009,
      price: 7882,
      image: "http://dummyimage.com/300x300.png/dddddd/000000",
      if_favorite: false,
      stock: 8,
    },
    {
      id: 4,
      car_make_name: "Chevrolet",
      car_model_name: "Silverado 3500HD",
      car_model_year: 2006,
      price: 5093,
      image: "http://dummyimage.com/300x300.png/dddddd/000000",
      if_favorite: false,
      stock: 5,
    },
    {
      id: 5,
      car_make_name: "Mazda",
      car_model_name: "B-Series Plus",
      car_model_year: 1994,
      price: 5584,
      image: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
      if_favorite: false,
      stock: 8,
    },
    {
      id: 6,
      car_make_name: "Porsche",
      car_model_name: "Cayenne",
      car_model_year: 2012,
      price: 4417,
      image: "http://dummyimage.com/300x300.png/ff4444/ffffff",
      if_favorite: false,
      stock: 7,
    },
    {
      id: 7,
      car_make_name: "Maserati",
      car_model_name: "430",
      car_model_year: 1991,
      price: 3818,
      image: "http://dummyimage.com/300x300.png/dddddd/000000",
      if_favorite: false,
      stock: 9,
    },
    {
      id: 8,
      car_make_name: "Honda",
      car_model_name: "Pilot",
      car_model_year: 2006,
      price: 3348,
      image: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
      if_favorite: false,
      stock: 4,
    },
    {
      id: 9,
      car_make_name: "Subaru",
      car_model_name: "Loyale",
      car_model_year: 1990,
      price: 6604,
      image: "http://dummyimage.com/300x300.png/cc0000/ffffff",
      if_favorite: false,
      stock: 8,
    },
    {
      id: 10,
      car_make_name: "Ford",
      car_model_name: "F-Series",
      car_model_year: 1994,
      price: 442,
      image: "http://dummyimage.com/300x300.png/dddddd/000000",
      if_favorite: false,
      stock: 11,
    },
    {
      id: 11,
      car_make_name: "GMC",
      car_model_name: "Yukon XL 2500",
      car_model_year: 2001,
      price: 7256,
      image: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
      if_favorite: false,
      stock: 9,
    },
    {
      id: 12,
      car_make_name: "Lexus",
      car_model_name: "IS",
      car_model_year: 2011,
      price: 2009,
      image: "http://dummyimage.com/300x300.png/dddddd/000000",
      if_favorite: false,
      stock: 3,
    },
    {
      id: 13,
      car_make_name: "Chevrolet",
      car_model_name: "Suburban 2500",
      car_model_year: 2010,
      price: 1269,
      image: "http://dummyimage.com/300x300.png/ff4444/ffffff",
      if_favorite: false,
      stock: 6,
    },
    {
      id: 14,
      car_make_name: "Ford",
      car_model_name: "Club Wagon",
      car_model_year: 1997,
      price: 7580,
      image: "http://dummyimage.com/300x300.png/ff4444/ffffff",
      if_favorite: false,
      stock: 6,
    },
    {
      id: 15,
      car_make_name: "Suzuki",
      car_model_name: "Vitara",
      car_model_year: 2002,
      price: 1934,
      image: "http://dummyimage.com/300x300.png/cc0000/ffffff",
      if_favorite: false,
      stock: 7,
    },
    {
      id: 16,
      car_make_name: "Lexus",
      car_model_name: "LS",
      car_model_year: 2008,
      price: 8598,
      image: "http://dummyimage.com/300x300.png/dddddd/000000",
      if_favorite: false,
      stock: 5,
    },
    {
      id: 17,
      car_make_name: "Lexus",
      car_model_name: "LX",
      car_model_year: 2005,
      price: 8801,
      image: "http://dummyimage.com/300x300.png/ff4444/ffffff",
      if_favorite: false,
      stock: 2,
    },
    {
      id: 18,
      car_make_name: "Ford",
      car_model_name: "Thunderbird",
      car_model_year: 1989,
      price: 4596,
      image: "http://dummyimage.com/300x300.png/ff4444/ffffff",
      if_favorite: false,
      stock: 4,
    },
    {
      id: 19,
      car_make_name: "Toyota",
      car_model_name: "Tacoma",
      car_model_year: 2010,
      price: 947,
      image: "http://dummyimage.com/300x300.png/ff4444/ffffff",
      if_favorite: false,
      stock: 11,
    },
    {
      id: 20,
      car_make_name: "Honda",
      car_model_name: "Fit",
      car_model_year: 2007,
      price: 5834,
      image: "http://dummyimage.com/300x300.png/cc0000/ffffff",
      if_favorite: false,
      stock: 15,
    },
    {
      id: 21,
      car_make_name: "Chrysler",
      car_model_name: "Concorde",
      car_model_year: 1996,
      price: 7937,
      image: "http://dummyimage.com/300x300.png/cc0000/ffffff",
      if_favorite: false,
      stock: 13,
    },
    {
      id: 22,
      car_make_name: "Geo",
      car_model_name: "Prizm",
      car_model_year: 1994,
      price: 9643,
      image: "http://dummyimage.com/300x300.png/cc0000/ffffff",
      if_favorite: false,
      stock: 3,
    },
    {
      id: 23,
      car_make_name: "Toyota",
      car_model_name: "Paseo",
      car_model_year: 1997,
      price: 5686,
      image: "http://dummyimage.com/300x300.png/dddddd/000000",
      if_favorite: false,
      stock: 5,
    },
    {
      id: 24,
      car_make_name: "GMC",
      car_model_name: "Rally Wagon 2500",
      car_model_year: 1993,
      price: 4441,
      image: "http://dummyimage.com/300x300.png/dddddd/000000",
      if_favorite: false,
      stock: 5,
    },
    {
      id: 25,
      car_make_name: "Mazda",
      car_model_name: "MPV",
      car_model_year: 2003,
      price: 4571,
      image: "http://dummyimage.com/300x300.png/cc0000/ffffff",
      if_favorite: false,
      stock: 2,
    },
    {
      id: 26,
      car_make_name: "Pontiac",
      car_model_name: "Bonneville",
      car_model_year: 2001,
      price: 5464,
      image: "http://dummyimage.com/300x300.png/ff4444/ffffff",
      if_favorite: false,
      stock: 4,
    },
    {
      id: 27,
      car_make_name: "Mercedes-Benz",
      car_model_name: "E-Class",
      car_model_year: 1990,
      price: 857,
      image: "http://dummyimage.com/300x300.png/ff4444/ffffff",
      if_favorite: false,
      stock: 12,
    },
    {
      id: 28,
      car_make_name: "Pontiac",
      car_model_name: "1000",
      car_model_year: 1986,
      price: 8132,
      image: "http://dummyimage.com/300x300.png/cc0000/ffffff",
      if_favorite: false,
      stock: 9,
    },
    {
      id: 29,
      car_make_name: "Mercedes-Benz",
      car_model_name: "E-Class",
      car_model_year: 1991,
      price: 5391,
      image: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
      if_favorite: false,
      stock: 12,
    },
    {
      id: 30,
      car_make_name: "Toyota",
      car_model_name: "4Runner",
      car_model_year: 2010,
      price: 1689,
      image: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
      if_favorite: false,
      stock: 10,
    },
    {
      id: 31,
      car_make_name: "Ford",
      car_model_name: "Freestar",
      car_model_year: 2004,
      price: 3794,
      image: "http://dummyimage.com/300x300.png/ff4444/ffffff",
      if_favorite: false,
      stock: 1,
    },
    {
      id: 32,
      car_make_name: "Mitsubishi",
      car_model_name: "Mighty Max Macro",
      car_model_year: 1993,
      price: 4569,
      image: "http://dummyimage.com/300x300.png/cc0000/ffffff",
      if_favorite: false,
      stock: 1,
    },
    {
      id: 33,
      car_make_name: "Mercedes-Benz",
      car_model_name: "SLK-Class",
      car_model_year: 2001,
      price: 8535,
      image: "http://dummyimage.com/300x300.png/cc0000/ffffff",
      if_favorite: false,
      stock: 2,
    },
    {
      id: 34,
      car_make_name: "Ford",
      car_model_name: "Edge",
      car_model_year: 2011,
      price: 9503,
      image: "http://dummyimage.com/300x300.png/ff4444/ffffff",
      if_favorite: false,
      stock: 13,
    },
    {
      id: 35,
      car_make_name: "Isuzu",
      car_model_name: "Trooper",
      car_model_year: 1997,
      price: 6535,
      image: "http://dummyimage.com/300x300.png/ff4444/ffffff",
      if_favorite: false,
      stock: 2,
    },
    {
      id: 36,
      car_make_name: "Dodge",
      car_model_name: "Nitro",
      car_model_year: 2011,
      price: 9105,
      image: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
      if_favorite: false,
      stock: 10,
    },
    {
      id: 37,
      car_make_name: "Toyota",
      car_model_name: "Land Cruiser",
      car_model_year: 2002,
      price: 1024,
      image: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
      if_favorite: false,
      stock: 6,
    },
    {
      id: 38,
      car_make_name: "Toyota",
      car_model_name: "Highlander Hybrid",
      car_model_year: 2007,
      price: 4081,
      image: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
      if_favorite: false,
      stock: 9,
    },
    {
      id: 39,
      car_make_name: "Ford",
      car_model_name: "F350",
      car_model_year: 1994,
      price: 3393,
      image: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
      if_favorite: false,
      stock: 1,
    },
    {
      id: 40,
      car_make_name: "GMC",
      car_model_name: "Sierra 3500",
      car_model_year: 2006,
      price: 1968,
      image: "http://dummyimage.com/300x300.png/dddddd/000000",
      if_favorite: false,
      stock: 7,
    },
    {
      id: 41,
      car_make_name: "Mitsubishi",
      car_model_name: "Galant",
      car_model_year: 2011,
      price: 4003,
      image: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
      if_favorite: false,
      stock: 6,
    },
    {
      id: 42,
      car_make_name: "Hyundai",
      car_model_name: "Sonata",
      car_model_year: 2002,
      price: 990,
      image: "http://dummyimage.com/300x300.png/dddddd/000000",
      if_favorite: false,
      stock: 11,
    },
    {
      id: 43,
      car_make_name: "Ford",
      car_model_name: "Taurus",
      car_model_year: 1998,
      price: 6383,
      image: "http://dummyimage.com/300x300.png/ff4444/ffffff",
      if_favorite: false,
      stock: 9,
    },
    {
      id: 44,
      car_make_name: "Ford",
      car_model_name: "Bronco II",
      car_model_year: 1989,
      price: 3493,
      image: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
      if_favorite: false,
      stock: 8,
    },
    {
      id: 45,
      car_make_name: "Cadillac",
      car_model_name: "CTS",
      car_model_year: 2012,
      price: 513,
      image: "http://dummyimage.com/300x300.png/dddddd/000000",
      if_favorite: false,
      stock: 1,
    },
    {
      id: 46,
      car_make_name: "Dodge",
      car_model_name: "Ram Van 2500",
      car_model_year: 1998,
      price: 9879,
      image: "http://dummyimage.com/300x300.png/dddddd/000000",
      if_favorite: false,
      stock: 13,
    },
    {
      id: 47,
      car_make_name: "Chevrolet",
      car_model_name: "Express 3500",
      car_model_year: 2004,
      price: 2438,
      image: "http://dummyimage.com/300x300.png/cc0000/ffffff",
      if_favorite: false,
      stock: 11,
    },
    {
      id: 48,
      car_make_name: "Mercedes-Benz",
      car_model_name: "S-Class",
      car_model_year: 2009,
      price: 5892,
      image: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
      if_favorite: false,
      stock: 3,
    },
    {
      id: 49,
      car_make_name: "Infiniti",
      car_model_name: "Q",
      car_model_year: 2004,
      price: 484,
      image: "http://dummyimage.com/300x300.png/ff4444/ffffff",
      if_favorite: false,
      stock: 4,
    },
    {
      id: 50,
      car_make_name: "Mazda",
      car_model_name: "RX-8",
      car_model_year: 2011,
      price: 1922,
      image: "http://dummyimage.com/300x300.png/cc0000/ffffff",
      if_favorite: false,
      stock: 8,
    },
  ],
};
